### PR TITLE
Key sequences

### PR DESCRIPTION
**Pull request by Martin-Zeithaml**
## Proposed changes

This PR addresses Issue: [https://github.com/zowe/zlux/issues/698](https://github.com/zowe/zlux/issues/698)

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets the "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zlux/blob/master/CONTRIBUTING.md))
- [ ] Relevant update to CHANGELOG.md

## Testing
Testing was done manually only - at this moment there are no automated test for TN3270.
- No file provided - OK
- Invalid JSON syntax - OK
- Key sequence with prompt - OK
- Key sequence with Enter - OK

## Further comments
- tslint was run and all was fixed to get no warning => there are many "lint" changes
  -  ```lint-npm``` was added to scripts (otherwise it was scanning the local node_modules)
- [Wiki page for the feature](https://github.com/Martin-Zeithaml/tn3270-ng2/wiki/Key-Sequences)

### CODE REVIEW

**Review by 1000TurquoisePogs — CHANGES_REQUESTED** [review]
Good functionality but two problems:
_keySequences.json should be moved here https://github.com/zowe/tn3270-ng2/tree/v1.x/staging/config/storageDefaults/sessions
Because that will have it apply by default to all users.

Secondly, it appears you used an editor which applied style changes on save, which basically changed most of the contents of the files. This is against our practices because it makes git history more time consuming to follow.

**Comment by Martin-Zeithaml** [comment]
The ```_keySequences.json``` definition was moved to ```config/storageDefaults/sessions/```

The high number of changes was done manually due to the lint warnings, the editor (VSCode) did not applied any style.

**Comment by 1000TurquoisePogs** [comment]
Thanks for the fix, but the whitespace changes should still be reverted as it goes against our contributing guidelines: https://github.com/zowe/zlux/blob/master/CONTRIBUTING.md#whitespacing-syntax-and-linting

**Comment by 1000TurquoisePogs** [comment]
Might be better to just recreate the PR? I was going to do the same but got busy.

**Review by 1000TurquoisePogs — APPROVED** [review]
This looks great to me now, thank you.

**Pull request merged**
